### ISSUE TITLE
Can't get the target

### ISSUE THREAD

**Issue by Tyler-ytr** [OpenNetLab/gym#6]
I clicked the [AzurePipeline](https://dev.azure.com/OpenNetLab/ONL-github/_build/results?buildId=342&view=results) from README, but it is impossible to download anything from the target. Well,There is nothing wrong with my Internet.

**Comment by Pterosaur** [comment]
Thanks for your report this issue. For better experience, we have uploaded the `target` to Github Release and update our Readme.
You can directly get the pre-compiled binary by
```
wget https://github.com/OpenNetLab/gym/releases/latest/download/target.tar.gz
```
and uncompress it by
```
tar -xvzf target.tar.gz
```
